name: build-ci

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install libraries
        id: setuptools
        run: npm install
        continue-on-error: true
      - name: Build all files
        id: buildall
        run: npm run buildall
        continue-on-error: true
      - name: Check Failures
        if: ${{ failure() }}
        run: echo "Build failed"
